name: Flutter Android Release Build

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /opt/android-sdk
      PATH: $PATH:/opt/flutter/bin:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: stable
          flutter-version: 3.24.3
      - run: flutter --version

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android release
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
