name: Flutter Android Release Build on Windows

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-android:
    runs-on: windows-latest

    env:
      ANDROID_HOME: C:\Android\Sdk
      PATH: C:\Android\Sdk\cmdline-tools\latest\bin;C:\Android\Sdk\platform-tools;C:\flutter\bin;${{ env.PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: stable
          flutter-version: 3.24.3
      - run: flutter --version

      - name: Install Android SDK Command-Line Tools
        run: |
          choco install -y openjdk11
          choco install -y android-sdk
          echo "sdkmanager.bat --licenses" | call
          sdkmanager.bat "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android release
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build\app\outputs\flutter-apk\app-release.apk

      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build\\app\\outputs\\flutter-apk\\app-release.apk"
          tag: v1.0.29
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
